### ISSUE TITLE
[Tracking Issue] Sparse TIR progress checker (Mar)

### ISSUE THREAD

**Issue by yzh119** [uwsampl/sparsetir#1]
- [x] Compatibility
  - [x] `blockize`
  - [x] `tensorize`
  - [x] `compute_at`
  - [x] `cache_read/write`.
  - [x] `CompactBufferRegion`
  - [x] `specialize`
- [x] RGCN + tensorization.
- [x] BSRMM + tensorization.
- [x] Lower Sparse TIR buffers.
- [x] Lower atomics.
- [x] Lower binary search.
- [x] Horizontal fusion.
- [ ] Special case of FusedAxis and FlattenedAxis.
- [x] Add banded axis.
