### ISSUE TITLE
[Tracking Issue] Algebraic Axis

### ISSUE THREAD

**Issue by yzh119** [uwsampl/sparsetir#5]
- [x] Refactor Axis class.
- [x] Design the interface for flatten axis.
- [ ] Support multiple parent axes?
