### ISSUE TITLE
[Tracking Issue] Refactor `LowerSparseIter` pass

### ISSUE THREAD

**Issue by yzh119** [uwsampl/sparsetir#66]
# Pitch
The current implementation of sparse iteration lowering, also known as the `LowerSparseIter` pass, was written in a [single pass manner](https://github.com/uwsampl/sparsetir/blob/7ec3bca12221f2f34da17430c690ff25bda12747/src/tir/transforms/lower_sparse_iter.cc).

The `IterTransformer` mutator performs all the rewrites and it's error-prone and hard to maintain. We should refactor the pass to several smaller passes that perform a sub-step of the whole pass:
1. [ ] Auxiliary Buffer Materialization
2. [ ] Nested Loop Generation
3. [ ] Nested Block Generation
4. [ ] Read/Write region analysis
5. [ ] Binary Search Block generation
6. [ ] Guard generation
